#!/usr/bin/env bash

set -e
cd "$(dirname "0")"

function displayStartMessage() {
	echo "Usage: de <command> [options]"
	echo ""
	echo "Commands:"
	echo "   de start            Start the development environment"
	echo "   de build            Build the development environment"
}

function executeCommand() {
	if [ -f ./.scripts/"$1".sh ]; then
		bash ./.scripts/"$1".sh
	else
		displayStartMessage
	fi
}

executeCommand "$1"