version: "3.3"

services:
  client:
    image: development-environment-client
    build:
      dockerfile: docker/client/Dockerfile
      context: ../
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./Projects:/home/dev/Projects
